version: '3'

services:
  db:
    image: mysql:8.0.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Respons11
      MYSQL_DATABASE: rest-api
      MYSQL_USER: user
      MYSQL_PASSWORD: Azerty11
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_SERVER: 'localhost'
      DB_USER: 'user'
      DB_PASSWORD: 'Azerty11'
      DB_NAME: 'rest-api'
      JWT_SECRET: 'secret'

volumes:
  db_data: