version: '3'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Respons11
      MYSQL_USER: user
      MYSQL_PASSWORD: Azerty11
    volumes:
      - ./data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      DB_SERVER: 'db'
      DB_USER: 'root'
      DB_PASSWORD: 'Respons11'
      DB_NAME: 'rest_api'
      JWT_SECRET: 'secret'
    depends_on:
      db:
        condition: service_healthy