name: Docker Compose Test

on:
  push:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:latest
        options: --privileged
        ports:
          - 3307:3306
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start Docker Compose
        run: docker-compose up -d

      - name: Stop Docker Compose
        run: docker-compose down